CREATE TABLE users (

id SERIAL PRIMARY KEY,

full_name VARCHAR(120) NOT NULL,

mobile VARCHAR(15) UNIQUE NOT NULL,

email VARCHAR(150) UNIQUE NOT NULL,

password TEXT NOT NULL,

role VARCHAR(30) DEFAULT 'customer',

status BOOLEAN DEFAULT TRUE,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);